spring.application.name=mangment_pfarmacy_v2

spring.datasource.url=jdbc:postgresql://localhost:5432/pharmacie_sys
spring.datasource.username=postgres
spring.datasource.password =rayen
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto =<create | create-drop | update | validate | none>
spring.jpa.hibernate.ddl-auto =update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=9090

# JWT Configuration
jwt.secret=your_super_secret_jwt_key_min_256_bits_long_to_be_secure_12345678901234567890
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# SuperAdmin Bootstrap
superadmin.init.secret=SuperAdminSecureInitKey2024

# Flouci payment gateway
flouci.app-token=1ebad78c-5d14-449f-9e58-34c2684d72c2
flouci.app-secret=${SECRET_FLOUCI_TOKEN:}
flouci.success-link=http://localhost:3000/admin/abonnement/success
flouci.fail-link=http://localhost:3000/admin/abonnement/failed
flouci.developer-tracking-id=e0d9304a-4578-427a-ba7e-16cf760c08ae
flouci.accept-card=true
flouci.session-timeout-secs=1200
